SELECT
SA.SALES_AGENT_ID,
CUST.CUSTOMER_ID,
SA.NAME AS AGENT_NAME,
CUST.CUST_NAME,
SUM((SA.SALEC_COMMISION_PCT*ORD.PURCHASE_AMT)::number(32,2))COMMISION_EARNED
FROM
{{ ref('sales_agent') }} AS SA 
INNER JOIN {{ ref('orders') }} ORD
ON ORD.SALES_AGENT_ID =SA.SALES_AGENT_ID
INNER JOIN {{ source('sales_sources', 'customer') }} CUST
ON CUST.CUSTOMER_ID=ORD.CUSTOMER_ID  WHERE SA.CITY='New York'
GROUP BY 1,2,3,4
