{% macro run_insert_dummy(KPI_CATEGORY,KPI_ID,KPI_SUB_ID,KPI_DESCRIPTION,
KPI_CLASS,REPPOS,PULPOS,NCEPOS,NCOPOS,NEGATION_FLAG,FRACTION_FLAG) %}
{% set query %}
insert into PRC.DBT_NPATIL.T_MD_KPI_DETAILS(KPI_CATEGORY,KPI_ID,KPI_SUB_ID,KPI_DESCRIPTION,KPI_CLASS,
REPPOS,PULPOS,NCEPOS,NCOPOS,NEGATION_FLAG,FRACTION_FLAG) values(
'{{KPI_CATEGORY}}',
{{KPI_ID}},
'{{KPI_SUB_ID}}',
'{{KPI_DESCRIPTION}}',
'{{KPI_CLASS}}',
'{{REPPOS}}',
{{PULPOS}},
'{{NCEPOS}}',
'{{NCOPOS}}',
{{NEGATION_FLAG}},
{{FRACTION_FLAG}});
{% endset %}
{% do run_query(query) %}
{% endmacro %}
